version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
    groups:
      npm-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /studio
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
    groups:
      studio-minor-and-patch:
        update-types:
          - minor
          - patch
